/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dailydrivermanage;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zakir
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContainerPanel = new javax.swing.JPanel();
        LabelsContainerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        InputFieldsPanel = new javax.swing.JPanel();
        Date date = new Date(); //creating a new date variable
        SpinnerDateModel sm =  new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY); //setting hour of day
        jSpinner1 = new javax.swing.JSpinner(sm);
        PickupTXT = new javax.swing.JTextField();
        DestinationTXT = new javax.swing.JTextField();
        DriversIDTXT = new javax.swing.JTextField();
        PassengerTXT = new javax.swing.JTextField();
        AmountTXT = new javax.swing.JTextField();
        OptionalTipTXT = new javax.swing.JTextField();
        AccountTXT = new javax.swing.JTextField();
        TelephoneTXT = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        CancelBTN = new javax.swing.JButton();
        loadBTN = new javax.swing.JButton();
        InsertBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        ExportBTN = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        totalamountTXT = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TotalJobsTXT = new javax.swing.JLabel();
        TotalExpectedText = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SecondTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContainerPanel.setName("ContainerPanel"); // NOI18N

        LabelsContainerPanel.setBackground(new java.awt.Color(51, 102, 255));
        LabelsContainerPanel.setAlignmentY(0.0F);
        LabelsContainerPanel.setName("PanelTitles"); // NOI18N
        LabelsContainerPanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pick Up Point");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel2);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Destination");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel3);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Driver's ID");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Passenger Name");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel5);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Amount");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel6);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Optional Tip");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel7);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Account");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel8);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Telephone");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setPreferredSize(new java.awt.Dimension(85, 24));
        LabelsContainerPanel.add(jLabel9);

        InputFieldsPanel.setBackground(new java.awt.Color(51, 255, 255));
        InputFieldsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        InputFieldsPanel.setAlignmentX(0.0F);
        InputFieldsPanel.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "HH:mm:ss");	// using DateEditor to set the time format
        jSpinner1.setEditor(de);	//Setting the final DateEditor to default editor.
        jSpinner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jSpinner1.setMinimumSize(null);
        jSpinner1.setPreferredSize(null);
        InputFieldsPanel.add(jSpinner1);

        PickupTXT.setMinimumSize(null);
        PickupTXT.setPreferredSize(null);
        InputFieldsPanel.add(PickupTXT);

        DestinationTXT.setMinimumSize(null);
        DestinationTXT.setPreferredSize(null);
        InputFieldsPanel.add(DestinationTXT);

        DriversIDTXT.setMinimumSize(null);
        DriversIDTXT.setPreferredSize(null);
        DriversIDTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DriversIDTXTKeyTyped(evt);
            }
        });
        InputFieldsPanel.add(DriversIDTXT);

        PassengerTXT.setMinimumSize(null);
        PassengerTXT.setPreferredSize(null);
        InputFieldsPanel.add(PassengerTXT);

        AmountTXT.setMinimumSize(null);
        AmountTXT.setPreferredSize(null);
        AmountTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AmountTXTKeyTyped(evt);
            }
        });
        InputFieldsPanel.add(AmountTXT);

        OptionalTipTXT.setMinimumSize(null);
        OptionalTipTXT.setPreferredSize(null);
        InputFieldsPanel.add(OptionalTipTXT);

        AccountTXT.setMaximumSize(null);
        AccountTXT.setMinimumSize(null);
        AccountTXT.setPreferredSize(null);
        InputFieldsPanel.add(AccountTXT);

        TelephoneTXT.setMinimumSize(new java.awt.Dimension(0, 24));
        TelephoneTXT.setPreferredSize(new java.awt.Dimension(101, 28));
        InputFieldsPanel.add(TelephoneTXT);

        panel1.setBackground(new java.awt.Color(102, 255, 255));

        CancelBTN.setText("Cancel");
        CancelBTN.setToolTipText("Unselect/Reset");
        CancelBTN.setFocusable(false);

        loadBTN.setText("Load");
        loadBTN.setFocusable(false);
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        InsertBTN.setText("Insert");
        InsertBTN.setToolTipText("Insert Data");
        InsertBTN.setAlignmentY(0.0F);
        InsertBTN.setFocusable(false);
        InsertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTNActionPerformed(evt);
            }
        });

        SaveBTN.setText("Save");
        SaveBTN.setToolTipText("Save/Update");
        SaveBTN.setAlignmentY(0.0F);
        SaveBTN.setFocusable(false);

        ExportBTN.setText("Export");
        ExportBTN.setToolTipText("Export");
        ExportBTN.setFocusable(false);
        ExportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(loadBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InsertBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Pick Up Point", "Destination", "Driver's ID", "Passenger Name", "Amount", "Optional Tip", "Account", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        MainTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12)); //Changing Header Font
        MainTable.getTableHeader().setOpaque(false);
        MainTable.getTableHeader().setBackground(new Color(68, 253, 159));
        MainTable.getTableHeader().setForeground(new Color(0, 0, 0));
        MainTable.setDoubleBuffered(true);
        MainTable.setRowHeight(25);
        MainTable.setShowGrid(true);
        MainTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(MainTable);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalamountTXT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        totalamountTXT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalamountTXT.setText("£0.00");
        totalamountTXT.setToolTipText("");
        totalamountTXT.setAlignmentX(0.5F);
        totalamountTXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalamountTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(totalamountTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 80, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Total for the day");
        jLabel12.setToolTipText("");
        jLabel12.setAlignmentX(0.5F);
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Total jobs of the day");
        jLabel13.setToolTipText("");
        jLabel13.setAlignmentX(0.5F);
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 30));

        TotalJobsTXT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TotalJobsTXT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalJobsTXT.setText("0");
        TotalJobsTXT.setToolTipText("");
        TotalJobsTXT.setAlignmentX(0.5F);
        TotalJobsTXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalJobsTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(TotalJobsTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 30));

        TotalExpectedText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TotalExpectedText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalExpectedText.setText("£0.00");
        TotalExpectedText.setToolTipText("");
        TotalExpectedText.setAlignmentX(0.5F);
        TotalExpectedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TotalExpectedText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(TotalExpectedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 80, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Expected % for the day");
        jLabel16.setToolTipText("");
        jLabel16.setAlignmentX(0.5F);
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Driver");
        jLabel17.setToolTipText("");
        jLabel17.setAlignmentX(0.5F);
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 63, 20));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Jobs done");
        jLabel19.setToolTipText("");
        jLabel19.setAlignmentX(0.5F);
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 110, 63, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Takings");
        jLabel20.setToolTipText("");
        jLabel20.setAlignmentX(0.5F);
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 110, 63, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("%");
        jLabel21.setToolTipText("");
        jLabel21.setAlignmentX(0.5F);
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 110, 63, 20));

        SecondTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver", "Takings", "%", "Jobs done"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SecondTable.setGridColor(new java.awt.Color(0, 0, 0));
        SecondTable.setInheritsPopupMenu(true);
        SecondTable.getTableHeader().setResizingAllowed(false);
        SecondTable.getTableHeader().setReorderingAllowed(false);
        SecondTable.setTableHeader(null);
        jScrollPane2.setViewportView(SecondTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 260));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelsContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputFieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addComponent(LabelsContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InputFieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContainerPanel.getAccessibleContext().setAccessibleName("ContainerPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTNActionPerformed
        DefaultTableModel table = (DefaultTableModel) MainTable.getModel(); //Getting Maintable Model.
        table.addRow(Functionalities.inserting(new JSpinner.DateEditor(jSpinner1, "hh:mm").getFormat().format(jSpinner1.getValue()),
                PickupTXT.getText(), DestinationTXT.getText(),
                DriversIDTXT.getText(), PassengerTXT.getText(), AmountTXT.getText(), OptionalTipTXT.getText(),
                AccountTXT.getText(), TelephoneTXT.getText()));

        DefaultTableModel Model = (DefaultTableModel) SecondTable.getModel(); //Getting Second Table Model.
        SecondTable.setModel(Functionalities.SecondInserting(Integer.valueOf(DriversIDTXT.getText().toString()),
                Float.valueOf(AmountTXT.getText()), Model));

        Functionalities.TotalCount(totalamountTXT, TotalJobsTXT, TotalExpectedText, (DefaultTableModel) SecondTable.getModel());

    }//GEN-LAST:event_InsertBTNActionPerformed

    private void DriversIDTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DriversIDTXTKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c))) {
            evt.consume();
        }

    }//GEN-LAST:event_DriversIDTXTKeyTyped

    private void AmountTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountTXTKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == '.'))) {
            evt.consume();
        }
    }//GEN-LAST:event_AmountTXTKeyTyped

    private void ExportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportBTNActionPerformed
// parent component of the dialog
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a csv file to save");

        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
           if (Functionalities.exportToCSV(MainTable,fileToSave.getAbsolutePath()) == true){
           JOptionPane.showMessageDialog(null, "Saved to " +fileToSave.getAbsolutePath() );

           
           }
        }

    }//GEN-LAST:event_ExportBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        String filepath = "";
        // create a File chooser
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            filepath = f.getPath(); // Get the File Path

        }
        // Parsing CSV.
        // These are variables.
        String file = filepath;
        BufferedReader reader = null;
        String line = "";
        try {
            reader = new BufferedReader(new FileReader(file));
            while ((line = reader.readLine()) != null) {
                String[] row = line.split(",");
                if (!line.contains("Pick Up Point")) { //Checking if it is Header or not. If it is header then skip.
                    DefaultTableModel table = (DefaultTableModel) MainTable.getModel(); //Getting Maintable Model.
                    table.addRow(row); // Adding into main table
                    DefaultTableModel secondtable = (DefaultTableModel) SecondTable.getModel(); //Getting Maintable Model.
                    Functionalities.SecondInserting(Integer.valueOf(row[3]), Float.valueOf(row[5]), secondtable); //Adding into Second Table
                    Functionalities.TotalCount(totalamountTXT, TotalJobsTXT, TotalExpectedText, (DefaultTableModel) SecondTable.getModel()); //Using SecondTable model so we can sum.

                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_loadBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountTXT;
    private javax.swing.JTextField AmountTXT;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JTextField DestinationTXT;
    private javax.swing.JTextField DriversIDTXT;
    private javax.swing.JButton ExportBTN;
    private javax.swing.JPanel InputFieldsPanel;
    private javax.swing.JButton InsertBTN;
    private javax.swing.JPanel LabelsContainerPanel;
    private javax.swing.JTable MainTable;
    private javax.swing.JTextField OptionalTipTXT;
    private javax.swing.JTextField PassengerTXT;
    private javax.swing.JTextField PickupTXT;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JTable SecondTable;
    private javax.swing.JTextField TelephoneTXT;
    private javax.swing.JLabel TotalExpectedText;
    private javax.swing.JLabel TotalJobsTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton loadBTN;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel totalamountTXT;
    // End of variables declaration//GEN-END:variables
}
